@REM Unreal Engine Build
echo ##CI_UE_HOME=%C:\Users\Saswat\Documents\GitHub\UnrealEngine%#

@REM Windows Publishing
echo ##APP_NAME=Creatospace#
echo ##APP_DESCRIPTION=Taking Your Communities to a Metaverse#
@REM The following is the app .exe generated by Unreal Engine build under Distribution\Windows
echo ##MSIX_EXE=Creatospace.exe#
echo ##MSIX_RESOURCES=C:\Users\Saswat\Documents\GitHub\Unreal2.0\logo150.png#
echo ##MSIX_LOGO_44=logo44.png#
echo ##MSIX_LOGO_150=logo150.png#
echo ##MSIX_APPLOGO=SampleLogo200x150.png#
echo ##MSIX_BGCOLOR_HEX=464646#
echo ##PUBLISHER=Creatospace Pvt. Ltd.#
echo ##PUBLISHER_ACCOUNT=CreatospacePvt.Ltd.Creatospace-Metaverseforcommuni#
echo ##PUBLISHER_FAMILY=CreatospacePvt.Ltd.Creatospace-Metaverseforcommuni_a87s875vpx0vw#
echo ##PUBLISHER_UUID=C33B5411-0EA0-491C-81CC-016C8BB05AA0#